POST http://localhost:8080/api/v1/order
Content-Type: application/json
Accept: application/json

{
  "paymentMethod": "card",
  "shipMethodId": 1,
  "couponCode": "WELCOME10",
  "idempotencyKey": "checkout-attempt-001",
  "shippingAddress": {
    "name": "John Doe",
    "country": "US",
    "province": "California",
    "city": "Los Angeles",
    "postalCode": "90001",
    "street": "123 Main St",
    "apartment": "Unit 4B",
    "phoneNumber": "1234567890"
  },
  "items": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

### GET ORDER
GET http://localhost:8080/api/v1/order/1

### UPDATE ORDER STATUS
PATCH http://localhost:8080/api/v1/order/1/status
Content-Type: application/json

{
  "status": "PROCESSING"
}
